os: osx
sudo: false

language: node_js
node_js:
  - "10"


before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.17.3
  - export PATH=$HOME/.yarn/bin:$PATH
  - cd gui

install: yarn install

script: yarn build


before_deploy:
- export FILE_TO_UPLOAD=$(ls _releases/-*.dmg)

deploy:
  provider: releases
  file_glob: true
  file: "${FILE_TO_UPLOAD}"
  skip_cleanup: true
  on:
    tags: true
      branch: finalrelease
